[package]
name = "oxabz-xkcd-wallpaper"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
shuttle-service = { version = "0.7.2", features = ["web-warp"] }
warp = "0.3.2"
xkcd-wallpaper-routes = {path = "../routes"}